### ISSUE TITLE
implement cosh

### ISSUE THREAD

**Issue by japaric** [japaric/libm#13]
Source: https://git.musl-libc.org/cgit/musl/tree/src/math/cosh.c

**Comment by Veykril** [comment]
I would like to try this one

**Comment by Veykril** [comment]
I would try to do this one and it's dependancy #18

**Comment by kirch7** [comment]
I am taking this one.

**Comment by kirch7** [comment]
I missed some information on the contributing file and bors could not close this issue. I think it can be solved because of #117
