### ISSUE TITLE
Organization of double-underscore functions?

### ISSUE THREAD

**Issue by porglezomp** [japaric/libm#76]
The double underscore functions `__sin`, `__cos`, `__rem_pio2`, etc. are used in many other functions.

• Should they get their own modules, or be in one support module?
• How should the modules and functions be named?

**Comment by porglezomp** [comment]
One data point in favor of not putting them all in *one* file: `__rem_pio2_large` is over 400 lines long.

My first instinct here is to maybe have `__sin`, `__cos`, `__sinf`, etc. in one module (`trig_internal` maybe?), and all of the `__rem_pio2` variants in one module, with other functions organized similarly as appropriate.

**Comment by japaric** [comment]
They can follow the same organization as the public functions (one file / module per function), but they shouldn't be part of the public API of the crate. That is they shouldn't be publicly re-exported in src/math and they shouldn't appear in the output of `cargo doc`.

Also note that #67 adds some of these helper functions (like rem_pio2_large).

**Comment by porglezomp** [comment]
Okay, following the precedent there we should remove double underscores. That leaves the issue though, there's both `cos` and `__cos`, should names that collide use a single underscore, or should we use some different naming convention?

**Comment by japaric** [comment]
I believe those two can be named k_sin and k_cos; the C source file says: "origin: FreeBSD /usr/src/lib/msun/src/k_sin.c" and the documentation says "kernel sin function".

**Comment by porglezomp** [comment]
In this case, I propose that we rename the `cosdf` and `sindf` to `k_cosf` and `k_sinf` respectively, since those are the FreeBSD names for those files, and I don't know what `df` means here.

**Comment by japaric** [comment]
@porglezomp SGTM

> (since it takes a double it's probably something like sin double->float)

My thoughts exactly.

**Comment by japaric** [comment]
Done in #67
