### ISSUE TITLE
mod.rs needs an isnan for f64

### ISSUE THREAD

**Issue by jackmott** [japaric/libm#94]
I was just going to add it myself but have no idea how.

**Comment by porglezomp** [comment]
Should we perhaps be using the `core::f32::is_nan` and `core::f64::is_nan` instead anyway? @japaric?

**Comment by maxdeviant** [comment]
I had a similar question on #96.

**Comment by japaric** [comment]
I believe this has been done already. (The code is using the `is_nan` method instead of free functions).

**Comment by porglezomp** [comment]
I think this needs to be fixed in the `CONTRIBUTING` file, I'll make a PR for that.
